package aufgabe4_src;


// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 07:49:06 PM MESZ 
//


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArbeitszeitEinheit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ArbeitszeitEinheit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Min."/>
 *     &lt;enumeration value="Std."/>
 *     &lt;enumeration value="Tag(e)"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ArbeitszeitEinheit")
@XmlEnum
public enum ArbeitszeitEinheit {

    @XmlEnumValue("Min.")
    MIN("Min."),
    @XmlEnumValue("Std.")
    STD("Std."),
    @XmlEnumValue("Tag(e)")
    TAG_E("Tag(e)");
    private final String value;

    ArbeitszeitEinheit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArbeitszeitEinheit fromValue(String v) {
        for (ArbeitszeitEinheit c: ArbeitszeitEinheit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
