package generated_classes;

/// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 07:49:06 PM MESZ 
//


import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Schwierigkeit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Schwierigkeit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="leicht"/>
 *     &lt;enumeration value="normal"/>
 *     &lt;enumeration value="schwer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Schwierigkeit")
@XmlEnum
public enum Schwierigkeit {

    @XmlEnumValue("leicht")
    LEICHT("leicht"),
    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("schwer")
    SCHWER("schwer");
    private final String value;

    Schwierigkeit(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Schwierigkeit fromValue(String v) {
        for (Schwierigkeit c: Schwierigkeit.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
